SELECT
  HOLDVIEW.SDDOCO HOLDVIEW_SDDOCO,
  HOLDVIEW.SDDCTO HOLDVIEW_SDDCTO,
  HOLDVIEW.SDKCOO HOLDVIEW_SDKCOO,
  HOLDVIEW.SDMCU HOLDVIEW_SDMCU,
  HOLDVIEW.SDLITM HOLDVIEW_SDLITM,
  HOLDVIEW.SDDSC1 HOLDVIEW_SDDSC1,
  HOLDVIEW.SDAN8 HOLDVIEW_SDAN8,
  HOLDVIEW.BILLTONAME HOLDVIEW_BILLTONAME,
  HOLDVIEW.SDVR01 HOLDVIEW_SDVR01,
  HOLDVIEW.SDSHAN HOLDVIEW_SDSHAN,
  HOLDVIEW.SHIPTONAME HOLDVIEW_SHIPTONAME,
  (TO_CHAR (HOLDVIEW.ADATE, N'YYYY') - 1900) * 1000 + TO_CHAR (HOLDVIEW.ADATE, N'DDD') HOLDVIEW_ADATE,
  (TO_CHAR (HOLDVIEW.PDATE, N'YYYY') - 1900) * 1000 + TO_CHAR (HOLDVIEW.PDATE, N'DDD') HOLDVIEW_PDATE,
  HOLDVIEW.UORG HOLDVIEW_UORG,
  HOLDVIEW.SDUOM HOLDVIEW_SDUOM,
  HOLDVIEW.SDUPRC HOLDVIEW_SDUPRC,
  HOLDVIEW.SDAEXP HOLDVIEW_SDAEXP,
  HOLDVIEW.SHHOLD HOLDVIEW_SHHOLD,
  HOLDVIEW.SDZON HOLDVIEW_SDZON,
  F5642B01.BA55REF3 F5642B01_BA55REF3,
  HOLDVIEW.SDLTTR HOLDVIEW_SDLTTR,
  HOLDVIEW.SDNXTR HOLDVIEW_SDNXTR,
  HOLDVIEW.FRTHDLCODE HOLDVIEW_FRTHDLCODE,
  HOLDVIEW.PARENTNUM HOLDVIEW_PARENTNUM,
  HOLDVIEW.PARENTNAME HOLDVIEW_PARENTNAME,
  HOLDVIEW.PRICINGUOM HOLDVIEW_PRICINGUOM,
  HOLDVIEW.SALESREP HOLDVIEW_SALESREP,
  HOLDVIEW.SALESPERSON HOLDVIEW_SALESPERSON,
  HOLDVIEW.SDTORG HOLDVIEW_SDTORG,
  MAX(FLOOR(TO_NUMBER (NULL))) ReportColumn1
FROM
  (
    select
      F4211.sddoco,
      F4211.sddcto,
      F4211.sdkcoo,
      F4211.sdmcu,
      F4211.sdan8,
      F4211.sdshan,
      F4211.sdlitm,
      F4211.SDDSC1,
      F4211.sduom,
      F4211.sdshpn,
      F4211.SDZON,
      F4211.SDTORG,
      F4211.SDVR01,
      F4211.sduorg / 1000 uorg,
      TO_DATE (TO_CHAR (F4211.sdpefj + 1900000), 'YYYYDDD') PDATE,
      CASE
        WHEN F4211.SDADDJ = 0 THEN null
        WHEN F4211.SDADDJ IS NULL THEN TO_DATE ('1900001', 'YYYYDDD')
        ELSE TO_DATE (TO_CHAR (F4211.SDADDJ + 1900000), 'YYYYDDD')
      END ADATE,
      F4211.sduprc,
      F4211.sdaexp,
      (
        select
          SN.abalph
        from
          proddta.F0101 SN
        where
          SN.aban8 = F4211.sdshan
      ) ShipToName,
      (
        select
          BN.abalph
        from
          proddta.F0101 BN
        where
          BN.aban8 = F4211.sdan8
      ) BillToName,
      F4201.SHHOLD,
      F4211.sdlttr,
      F4211.sdnxtr,
      (
        select
          SN.abac05
        from
          proddta.F0101 SN
        where
          SN.aban8 = F4211.sdan8
      ) SalesRep,
      (
        select
          F0005.drdl01
        from
          prodctl.F0005
        where
          F0005.drsy = '01'
          and F0005.drrt = '05'
          and F0005.drky in (
            select
              lpad (AN.abac05, 10, ' ')
            from
              proddta.F0101 AN
            where
              AN.aban8 = F4211.sdan8
          )
      ) SalesPerson,
      F4211.SDFRTH FRTHDLCODE,
      F4211.SDUOM4 PRICINGUOM,
      F4211.SDPA8 PARENTNUM,
      (
        select
          PN.abalph
        from
          proddta.F0101 PN
        where
          PN.aban8 = F4211.sdpa8
      ) PARENTNAME
    from
      proddta.F4211,
      PRODDTA.F4201
    where
      F4211.SDDOCO = F4201.SHDOCO
      AND F4211.SDDCTO = F4201.SHDCTO
      AND F4211.SDKCOO = F4201.SHKCOO
      AND (
        (F4201.sHHOLD in ('ZP', 'WP'))
        OR (F4211.SDZON = 'Y')
      )
      and F4211.sdco in ('00640', '00645')
      and F4211.sddcto in ('S1', 'SE', 'SZ')
      and F4211.sdlnty = 'S'
      and F4211.sdlttr <> '980'
  ) HOLDVIEW
  LEFT JOIN PRODDTA.F5642B01 F5642B01 ON (
    (
      (HOLDVIEW.SDSHPN = F5642B01.BASHPN)
      AND (HOLDVIEW.SDDOCO = F5642B01.BADOCO)
    )
    AND (HOLDVIEW.SDDCTO = F5642B01.BADCTO)
  )
  AND (
    SUBSTR (
      N'00000' || TO_CHAR (RTRIM (LTRIM (HOLDVIEW.SDKCOO))),
      LENGTH (TO_CHAR (RTRIM (LTRIM (HOLDVIEW.SDKCOO)))) + 1,
      5
    ) = F5642B01.BAKCOO
  )
GROUP BY
  HOLDVIEW.SDDOCO,
  HOLDVIEW.SDDCTO,
  HOLDVIEW.SDKCOO,
  HOLDVIEW.SDMCU,
  HOLDVIEW.SDLITM,
  HOLDVIEW.SDDSC1,
  HOLDVIEW.SDAN8,
  HOLDVIEW.BILLTONAME,
  HOLDVIEW.SDVR01,
  HOLDVIEW.SDSHAN,
  HOLDVIEW.SHIPTONAME,
  (TO_CHAR (HOLDVIEW.ADATE, N'YYYY') - 1900) * 1000 + TO_CHAR (HOLDVIEW.ADATE, N'DDD'),
  (TO_CHAR (HOLDVIEW.PDATE, N'YYYY') - 1900) * 1000 + TO_CHAR (HOLDVIEW.PDATE, N'DDD'),
  HOLDVIEW.UORG,
  HOLDVIEW.SDUOM,
  HOLDVIEW.SDUPRC,
  HOLDVIEW.SDAEXP,
  HOLDVIEW.SHHOLD,
  HOLDVIEW.SDZON,
  F5642B01.BA55REF3,
  HOLDVIEW.SDLTTR,
  HOLDVIEW.SDNXTR,
  HOLDVIEW.FRTHDLCODE,
  HOLDVIEW.PARENTNUM,
  HOLDVIEW.PARENTNAME,
  HOLDVIEW.PRICINGUOM,
  HOLDVIEW.SALESREP,
  HOLDVIEW.SALESPERSON,
  HOLDVIEW.SDTORG
ORDER BY
  HOLDVIEW_SDDOCO ASC,
  HOLDVIEW_SDDCTO ASC,
  HOLDVIEW_SDKCOO ASC,
  HOLDVIEW_SDMCU ASC,
  HOLDVIEW_SDLITM ASC,
  HOLDVIEW_SDDSC1 ASC,
  HOLDVIEW_SDAN8 ASC,
  HOLDVIEW_SDSHAN ASC,
  HOLDVIEW_ADATE ASC,
  HOLDVIEW_PDATE ASC,
  HOLDVIEW_UORG ASC,
  HOLDVIEW_SDUOM ASC,
  HOLDVIEW_SDUPRC ASC,
  HOLDVIEW_SDAEXP ASC,
  HOLDVIEW_BILLTONAME ASC,
  HOLDVIEW_SHIPTONAME ASC,
  HOLDVIEW_SHHOLD ASC,
  HOLDVIEW_SDLTTR ASC,
  HOLDVIEW_SDNXTR ASC,
  HOLDVIEW_FRTHDLCODE ASC,
  HOLDVIEW_PARENTNUM ASC,
  HOLDVIEW_PARENTNAME ASC,
  HOLDVIEW_PRICINGUOM ASC,
  HOLDVIEW_SALESREP ASC,
  HOLDVIEW_SALESPERSON ASC,
  HOLDVIEW_SDZON ASC,
  HOLDVIEW_SDTORG ASC,
  F5642B01_BA55REF3 ASC,
  HOLDVIEW_SDVR01 ASC